version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.1.0
  gh-release: escaletech/gh-conventional-release@0.1
  sq: escaletech/sonarqube@0.3

jobs:
  test:
    docker:
      - image: cimg/node:17.7
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test-ci
      - persist_to_workspace:
          root: .
          paths: [.]

workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters:
            &ci-filters { branches: { ignore: master }, tags: { ignore: /.*/ } }
      - sq/scanner:
          context: sonarqube
          attach-workspace: true
          requires: [test]
          filters: *ci-filters
      - orb-tools/lint:
          lint-dir: src
          filters: *ci-filters
      - orb-tools/shellcheck:
          filters: *ci-filters
      - orb-tools/pack:
          filters: *ci-filters

  dev:
    jobs:
      - test:
          filters:
            &dev-filters { branches: { only: master }, tags: { ignore: /.*/ } }
      - orb-tools/lint:
          lint-dir: src
          filters: *dev-filters
      - orb-tools/shellcheck:
          filters: *dev-filters
      - orb-tools/pack:
          filters: *dev-filters
          requires: [test]
      - orb-tools/publish-dev:
          filters: *dev-filters
          context: orb-publishing
          orb-name: escaletech/gh-conventional-release
          requires: [orb-tools/lint, orb-tools/shellcheck, orb-tools/pack]

  release:
    jobs:
      - orb-tools/pack:
          filters:
            &release-filters {
              branches: { ignore: /.*/ },
              tags: { only: /v.+/ },
            }
      - orb-tools/publish:
          filters: *release-filters
          context: orb-publishing
          orb-ref: escaletech/gh-conventional-release@${CIRCLE_TAG#v}
          attach-workspace: true
          requires: [orb-tools/pack]
      - gh-release/create-release:
          filters: *release-filters
          context: github-create-release
          requires: [orb-tools/publish]
